[tool.black]
line-length = 100
target-version = ["py38", "py39", "py310"]


[tool.isort]
profile = "black"
py_version = 38
line_length = 100
combine_as_imports = true
filter_files = true


[tool.pyright]
typeCheckingMode = "strict"
include = [
    "guardianbot",
    "*.py",
]

# this is one of the diagnostics that aren't enabled by default, even in strict mode
reportUnnecessaryTypeIgnoreComment = true

# it's unlikely that these will ever be enabled
# reportOverlappingOverload = false
reportPrivateUsage = false
# reportUnnecessaryIsInstance = false
# reportFunctionMemberAccess = false
reportMissingTypeStubs = false
# reportUnusedFunction = false
# reportUnusedClass = false
# reportConstantRedefinition = false
reportImportCycles = false
# reportIncompatibleMethodOverride = false
# reportIncompatibleVariableOverride = false

# FIXME: aiodns doesn't have type stubs
useLibraryCodeForTypes = true

# these are largely due to missing type hints
reportUnknownMemberType = false
reportUnknownArgumentType = false
