[tool.mypy]
ignore_missing_imports = true
show_column_numbers = true
show_error_codes = true
disallow_any_generics = true
disallow_incomplete_defs = true
check_untyped_defs = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_unreachable = true
strict_equality = true
namespace_packages = true
